# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=1000)),
                ('dose', models.CharField(max_length=1000)),
                ('drug_company', models.CharField(max_length=1000)),
                ('drug_pic', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('drug_usage', models.CharField(max_length=1000)),
            ],
        ),
    ]
