# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20180107_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='stock',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
