# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20180108_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='dose',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_usage',
            field=models.CharField(max_length=100),
        ),
    ]
