# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 12:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0004_auto_20180109_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post_slug', models.SlugField(allow_unicode=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('drug_slug', models.SlugField(allow_unicode=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='childcomment',
            name='parrent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='Product.Comment'),
        ),
        migrations.AddField(
            model_name='childcomment',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
