# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20180110_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childcomment',
            old_name='post_slug',
            new_name='drug_slug',
        ),
    ]
