# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20180110_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='drug',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='drug_ingredient',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='drug',
            name='drug_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='drug',
            name='over_the_counter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drug',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Product.Category'),
        ),
    ]
