# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infouser', to='user_profile.UserInfo'),
        ),
    ]
