# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0005_auto_20180118_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='deliver',
            field=models.CharField(choices=[('p', 'pick-up'), ('d', 'deliver')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='refill',
            name='more_refill_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
