# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0006_auto_20180118_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refill',
            old_name='deliver',
            new_name='choose_your_shipment_method',
        ),
    ]
