# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_answer_user'),
        ('refill', '0008_auto_20180119_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('Dr_name', models.CharField(max_length=50)),
                ('Dr_Phone_number', models.IntegerField(null=True)),
                ('Dr_adrress', models.CharField(max_length=100)),
                ('last_pharmacy', models.CharField(max_length=100)),
                ('last_pharmacy_adrress', models.CharField(max_length=100)),
                ('prescription', models.ImageField(blank=True, upload_to='')),
                ('more_refill', models.BooleanField(default=False)),
                ('more_refill_number', models.CharField(blank=True, max_length=20)),
                ('choose_your_shipment_method', models.CharField(choices=[('p', 'pick-up'), ('d', 'deliver')], default='p', max_length=1)),
                ('info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rx_info_user', to='user_profile.UserInfo')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
