# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0009_auto_20180208_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill',
            name='Dr_Phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=123, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='refill',
            name='choose_your_shipment_method',
            field=models.CharField(choices=[('p', 'pick-up'), ('d', 'deliver')], default='d', max_length=1),
        ),
    ]
