# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0011_auto_20180208_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='verify_with_DR',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='refill',
            name='Dr_name',
            field=models.CharField(help_text='only required if verifying with dr is selected', max_length=50),
        ),
    ]
