# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 01:12
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0012_auto_20180208_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill',
            name='Dr_Phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
