# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0013_auto_20180208_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill',
            name='Dr_adrress',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='refill',
            name='Dr_name',
            field=models.CharField(blank=True, help_text='only required if verifying with dr is selected', max_length=50),
        ),
    ]
