# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0014_auto_20180208_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='vedrify_with_Pharmacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refill',
            name='verify_with_prescription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='refill',
            name='last_pharmacy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='refill',
            name='last_pharmacy_adrress',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
