# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0016_auto_20180209_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newrx',
            name='vedrify_with_Pharmacy',
        ),
        migrations.RemoveField(
            model_name='newrx',
            name='verify_with_DR',
        ),
        migrations.RemoveField(
            model_name='newrx',
            name='verify_with_prescription',
        ),
        migrations.AddField(
            model_name='newrx',
            name='verify_optin',
            field=models.CharField(choices=[('d', 'doctor'), ('p', 'pharmacy'), ('pr', 'prescription')], default='d', max_length=2),
        ),
    ]
