# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0018_auto_20180209_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newrx',
            name='choose_your_shipment_method',
        ),
        migrations.AddField(
            model_name='newrx',
            name='Date_of_Birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
