# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0021_auto_20180212_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newrx',
            old_name='doctor_phone_number',
            new_name='dr_phone_number',
        ),
    ]
