# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0023_auto_20180212_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drug_dose',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
