# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0024_auto_20180216_0808'),
        ('refill', '0024_auto_20180216_0117'),
    ]

    operations = [
    ]
