# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-19 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0028_newrx_refill'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrx',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
