# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-19 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0029_newrx_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newrx',
            old_name='code',
            new_name='rx_number',
        ),
    ]
