# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0030_auto_20180219_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrx',
            name='cansel',
            field=models.BooleanField(default=False),
        ),
    ]
