# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-18 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0031_newrx_cansel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drug_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
