# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0033_newrx_shiping_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refill',
            name='more_refill',
        ),
        migrations.RemoveField(
            model_name='refill',
            name='more_refill_number',
        ),
        migrations.AlterField(
            model_name='refill',
            name='RX_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
