# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0034_auto_20180408_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refill',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='refill',
            name='paid',
        ),
        migrations.AddField(
            model_name='refill',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='refill',
            name='Phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True),
        ),
    ]
