# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 07:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0035_auto_20180408_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
