# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0036_auto_20180408_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refill',
            name='info',
        ),
    ]
