# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0040_auto_20180422_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrxasqeust',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='newrxasqeust',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newrxasqeust',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
