# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0041_auto_20180422_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newrxasqeust',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
