# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 14:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0042_auto_20180422_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrxasqeust',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
