# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 04:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0043_auto_20180422_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newrxasqeust',
            name='Date_of_Birth',
        ),
        migrations.RemoveField(
            model_name='refill',
            name='Date_of_Birth',
        ),
        migrations.AlterField(
            model_name='newrxasqeust',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
