# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0044_auto_20180605_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refill',
            name='RX_number',
        ),
        migrations.AddField(
            model_name='refill',
            name='Refill_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
