# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('drug_dose', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='emergency_med',
            name='drug_dose',
        ),
        migrations.RemoveField(
            model_name='emergency_med',
            name='drug_dose1',
        ),
        migrations.RemoveField(
            model_name='emergency_med',
            name='drug_dose2',
        ),
        migrations.RemoveField(
            model_name='emergency_med',
            name='drug_name',
        ),
        migrations.RemoveField(
            model_name='emergency_med',
            name='drug_name1',
        ),
        migrations.RemoveField(
            model_name='emergency_med',
            name='drug_name2',
        ),
        migrations.AddField(
            model_name='emergency_med',
            name='drug_num',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
