# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_auto_20180119_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency_med',
            name='drug_num',
        ),
    ]
