# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_remove_emergency_med_drug_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency_med',
            name='drugs',
            field=models.ManyToManyField(to='emergency.Drug'),
        ),
    ]
