# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_emergency_med_drugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency_med',
            name='drugs',
        ),
        migrations.AddField(
            model_name='drug',
            name='med',
            field=models.ManyToManyField(to='emergency.Emergency_Med'),
        ),
    ]
