# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0005_auto_20180119_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='med',
        ),
        migrations.AddField(
            model_name='drug',
            name='med',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emergency.Emergency_Med'),
        ),
    ]
