# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0007_auto_20180602_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency_as_guest',
            name='Date_of_Birth',
        ),
    ]
