# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 07:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20180317_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='consult_as_guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('question', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
