# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 22:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0005_auto_20180113_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('drug_slug', models.SlugField(allow_unicode=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('drug_slug', models.SlugField(allow_unicode=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercomment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('Medical_spa_name', models.CharField(max_length=50)),
                ('Phone_number', models.IntegerField(null=True)),
                ('info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compoundinfo', to='user_profile.UserInfo')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Compound_Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('drug_dose', models.CharField(max_length=20)),
                ('drug_percentage', models.CharField(max_length=20)),
                ('med', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalspa.Compound')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('drug_company', models.CharField(max_length=100)),
                ('drug_pic', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('drug_usage', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('slug', models.SlugField(allow_unicode=True, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='childcomment',
            name='parrent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spachild', to='medicalspa.Comment'),
        ),
        migrations.AddField(
            model_name='childcomment',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='userchildcomment', to=settings.AUTH_USER_MODEL),
        ),
    ]
