# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalspa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childcomment',
            name='parrent',
        ),
        migrations.RemoveField(
            model_name='childcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Drug',
        ),
        migrations.DeleteModel(
            name='ChildComment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
