# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180111_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='user_profile.UserInfo'),
        ),
    ]
