# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20180113_2038'),
        ('orders', '0005_auto_20180114_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='info',
        ),
        migrations.AddField(
            model_name='order',
            name='usinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usinfo', to='user_profile.UserInfo'),
        ),
    ]
