# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180117_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usinfo', to='user_profile.UserInfo'),
        ),
    ]
