# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shiping_method',
            field=models.CharField(choices=[('e', 'express one day shiping $7.5'), ('r', 'regular three day shiping')], default='r', max_length=50),
        ),
    ]
