# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-06 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20180219_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shiping_method',
            field=models.CharField(choices=[(7.5, 'express one day shiping $7.5'), (0, 'regular three day shiping')], default='r', max_length=50),
        ),
    ]
